name: run github_now_playing

on:
  workflow_dispatch:
  schedule:
   # Run every Tuesday at 0 UTC
    - cron: '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          ref: github_runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: | 
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: run python script
        env:
          _client_id: ${{ secrets._CLIENT_ID }}
          _client_secret: ${{ secrets._CLIENT_SECRET }}
          _redirect_uri: ${{ secrets._REDIRECT_URI }}
          _refresh_token: ${{ secrets._REFRESH_TOKEN }}

        run: python github_now_playing.py

      - name: commit log file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Action"
          git add github_now_playing.txt
          git commit -a -m "Latest GitHub Action Run"

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: github_runner